### PR TITLE
Test tally with auto-naming

### PR DESCRIPTION
**Pull request by krlmlr**
Requires https://github.com/tidyverse/dplyr/pull/3525, CC @romainfrancois.

### CODE REVIEW

**Comment by hadley** [comment]
This fails on purpose, right?

**Comment by krlmlr** [comment]
Looks like a test where the current implementation is inconsistent with _dplyr_:

``` r
library(tidyverse)
tibble(n = 1:3) %>% tally()
#> Using `n` as weighting variable
#> # A tibble: 1 x 1
#>      nn
#>   <int>
#> 1     6
dbplyr::memdb_frame(n = 1:3) %>% tally()
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.22.0 [:memory:]
#>      nn
#>   <int>
#> 1     3
```

<sup>Created on 2019-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Ah, it only works with dev dplyr

**Comment by hadley** [comment]
In the original PR, you thought this should belong in dbplyr, but given that the change is to code in dplyr (and it's clearly a dbplyr bug), I feel like it belongs in dplyr.

**Comment by krlmlr** [comment]
Works for me in the dev version too. Are you comfortable depending on dev dplyr here?

**Comment by hadley** [comment]
I think the test has to be conditional on the dplyr version because dbplyr needs to be released before dplyr.

**Comment by hadley** [comment]
I'll finish this off

**Comment by hadley** [comment]
See https://github.com/tidyverse/dplyr/issues/4076

**Pull request closed without merging**
