### PR TITLE
dbplyr issue 153

### PR DESCRIPTION
**Pull request by sverchkov**
Fixes issue #153

### CODE REVIEW

**Comment by hadley** [comment]
Are you interested in finishing this off? (Double checking since it's been a while, so I'm happy to finish it off if you're no longer interest. Just let me know either way)

**Comment by sverchkov** [comment]
If it's just a matter of catching it up to the current state of the master branch I can do that.

**Comment by hadley** [comment]
That plus putting a space after every `,` will be 95% of the work, I think.

**Comment by hadley** [comment]
Looks good! Can you please add a bullet to NEWS? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by sverchkov** [comment]
Ok. Also, should I commit changes in roxygen-generated files as part of the pull request?

**Comment by hadley** [comment]
Yes, please!

**Comment by sverchkov** [comment]
Should be all good now.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
