### PR TITLE
support `missing` argument in `if_else()`

### LINKED ISSUE #641: if_else missing keyword errors
The following code errors in dbplyr but shouldn't:

``` r
library(tidyverse)
library(dbplyr)

lf <- lazy_frame(a = c(1,2,3,NA))

lf %>% mutate(if_else(condition = a > 1, true = a, false = 1, missing = 1))
#> Error in if_else(condition = a > 1, true = a, false = 1, missing = 1): unused argument (missing = 1)
```

A simple `coalesce()` does the job for now, but putting this on the radar! 

<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by mgirlich**
Fixes #641

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Thanks. What's the impact on backends that might have implemented a custom translations for `if_else()`? (I don't know if this is a thing already.)

**Comment by mgirlich** [comment]
If a backend already has a custom translation for `if_else()` then the translation from the default backend should simply be overwritten. This is also what happens in this PR for MS SQL.
So, I don't think this has any consequences for other backends.

**Comment by krlmlr** [comment]
So, as long as nobody calls `if_else()` with four arguments, everything remains the same in this case?

**Comment by mgirlich** [comment]
Yes, nothing changes if you use less than four arguments resp. pass nothing to `missing`.

**Pull request merged**
