### PR TITLE
Turned window_order into S3 generic.

### PR DESCRIPTION
**Pull request by iangow**
- Imported from dplyr.
- Relates to #627.

### CODE REVIEW

**Comment by iangow** [comment]
> Thanks for your PR. By now there is a check in place whether `.data` in `window_order()` is a lazy table or not. So, there is no immediate need to turn `window_order()` into an S3 generic.

Thanks. Does this mean one can use `window_order()` with non-lazy tables?

**Comment by mgirlich** [comment]
No, but it gives a nicer error message for non-lazy tables. Hadley pointed out this should rather throw an error https://github.com/tidyverse/dplyr/issues/6146#issuecomment-1192825426.

**Comment by mgirlich** [comment]
It depends on the circumstances whether `arrange()` creates a warning or not. As there is no subquery generated in the example it would not make sense to create a warning. In this case it is fine to use `arrange()` as the result is also supposed to be arranged. Overall, it would probably make more sense to call `window_order()` before the `mutate()` and `arrange()` as last step.

**Comment by iangow** [comment]
Got it. The example below (same as above, but with a join to trigger a subquery) triggers the warning.

There are a lot of subtleties with `dbplyr` that I think are challenging for a single chapter in R4DS to get into (perhaps why they don't even discuss `window_order()` there).

To this end, I have done some work "translating" the O'Reilly book "SQL for Data Analysis" to `dbplyr` [here](https://iangow.github.io/sql_book). Using `dbplyr` means the reader can make all the plots included in the original book (these were done "behind the scenes" using Python or Tableau in the original book). Also I conjecture that many users would write more accurate SQL using `dbplyr` rather than SQL (see [here](https://github.com/iangow/notes/blob/main/ctes.qmd)).

``` r
library(DBI)
library(dbplyr)
library(tidyverse)

con <- DBI::dbConnect(duckdb::duckdb())

dbplyr::copy_nycflights13(con)
#> Creating table: airlines
#> Creating table: airports
#> Creating table: flights
#> Creating table: planes
#> Creating table: weather
flights <- tbl(con, "flights")
airlines <- tbl(con, "airlines")

flights |> 
  group_by(dest) |>  
  window_order(time_hour) |> 
  mutate(lead = lead(arr_delay),
         lag = lag(arr_delay)) |>
  inner_join(airlines, by = "carrier") |>
  show_query()
#> <SQL>
#> SELECT LHS.*, "name"
#> FROM (
#>   SELECT
#>     *,
#>     LEAD(arr_delay, 1, NULL) OVER (PARTITION BY dest ORDER BY time_hour) AS lead,
#>     LAG(arr_delay, 1, NULL) OVER (PARTITION BY dest ORDER BY time_hour) AS lag
#>   FROM flights
#> ) LHS
#> INNER JOIN airlines
#>   ON (LHS.carrier = airlines.carrier)

flights |> 
  group_by(dest) |>  
  arrange(time_hour) |> 
  mutate(lead = lead(arr_delay),
         lag = lag(arr_delay)) |>
  ungroup() |>
  inner_join(airlines, by = "carrier") |>
  show_query()
#> Warning: ORDER BY is ignored in subqueries without LIMIT
#> ℹ Do you need to move arrange() later in the pipeline or use window_order() instead?
#> <SQL>
#> SELECT LHS.*, "name"
#> FROM (
#>   SELECT
#>     *,
#>     LEAD(arr_delay, 1, NULL) OVER (PARTITION BY dest ORDER BY time_hour) AS lead,
#>     LAG(arr_delay, 1, NULL) OVER (PARTITION BY dest ORDER BY time_hour) AS lag
#>   FROM flights
#> ) LHS
#> INNER JOIN airlines
#>   ON (LHS.carrier = airlines.carrier)
```

<sup>Created on 2023-06-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Pull request closed without merging**
