### PR TITLE
Fix method consistency for `sql_select.DBIConnection()`

### PR DESCRIPTION
**Pull request by mgirlich**
To fix the CRAN check results.

### CODE REVIEW

**Comment by mgirlich** [comment]
@hadley this should fix the CRAN check results.

**Comment by hadley** [comment]
Thanks! Ok to do a patch release later today?

**Comment by mgirlich** [comment]
Yes, but there are two breaking changes:

* `sql_random()` is now deprecated. I used `lifecycle::deprecate_warn()` but this might need to change to `lifecycle::deprecate_soft()` then.
* The `vars` argument of `translate_sql()` has been removed after it threw an error for the last 7 years.

**Comment by mgirlich** [comment]
This is probably a bit easier. Thanks!

**Comment by hadley** [comment]
Now let me remember how to do that 😆

**Pull request merged**
