### PR TITLE
Shim for redshift values table support

### LINKED ISSUE #949: copy_inline() and copy_to() not working in AWS Redshift
copy_inline() and copy_to() do not work in AWS Redshift.
Generated SQL appears to be syntactically incompatible with Redshift PostgreSQL:

Error: Failed to prepare query: ERROR:  syntax error at or near ","
LINE 30: ...f64faee3fc', 'nc', '27607', '3', '035', 'p', 's', 'h', '3'),
                                                                       ^

### PR DESCRIPTION
**Pull request by ejneer**
fixes #949 

```r
copy_inline(con, head(mtcars[c("mpg", "cyl", "disp")])) %>% show_query()
```

before:
```sql
<SQL>
SELECT
  CAST("mpg" AS FLOAT) AS "mpg",
  CAST("cyl" AS FLOAT) AS "cyl",
  CAST("disp" AS FLOAT) AS "disp"
FROM (
  (
    SELECT NULL AS "mpg", NULL AS "cyl", NULL AS "disp"
    WHERE (0 = 1)
  )
  UNION ALL
  (
  VALUES
    (21.0, 6.0, 160.0),
    (21.0, 6.0, 160.0),
    (22.8, 4.0, 108.0),
    (21.4, 6.0, 258.0),
    (18.7, 8.0, 360.0),
    (18.1, 6.0, 225.0)
  )
) "values_table"
```

after:
```sql
<SQL>
SELECT
  CAST("mpg" AS FLOAT) AS "mpg",
  CAST("cyl" AS FLOAT) AS "cyl",
  CAST("disp" AS FLOAT) AS "disp"
FROM (
  (
    SELECT NULL AS "mpg", NULL AS "cyl", NULL AS "disp"
    WHERE (0 = 1)
  )
  UNION ALL
  ( SELECT 21.0, 6.0, 160.0 UNION ALL SELECT 21.0, 6.0, 160.0 UNION ALL SELECT 22.8, 4.0, 108.0 UNION ALL SELECT 21.4, 6.0, 258.0 UNION ALL SELECT 18.7, 8.0, 360.0 UNION ALL SELECT 18.1, 6.0, 225.0)
) "values_table"
```

### CODE REVIEW

**Comment by ejneer** [comment]
@mgirlich 
This just stuffs all values rows into one big sql string, feels a little hacky and results in a really long line in the generated sql. Is there a better way to `union all` the values together?

**Comment by ejneer** [comment]
Using `sql_clause` to create the selects / union all produces better formatted sql.

new after:
```sql
<SQL>
SELECT
  CAST("mpg" AS FLOAT) AS "mpg",
  CAST("cyl" AS FLOAT) AS "cyl",
  CAST("disp" AS FLOAT) AS "disp"
FROM (
  (
    SELECT NULL AS "mpg", NULL AS "cyl", NULL AS "disp"
    WHERE (0 = 1)
  )
  UNION ALL
  (
  SELECT 21.0, 6.0, 160.0
  UNION ALL 
  SELECT 21.0, 6.0, 160.0
  UNION ALL 
  SELECT 22.8, 4.0, 108.0
  UNION ALL 
  SELECT 21.4, 6.0, 258.0
  UNION ALL 
  SELECT 18.7, 8.0, 360.0
  UNION ALL 
  SELECT 18.1, 6.0, 225.0
  )
) "values_table"
```

**Comment by mgirlich** [comment]
@ejneer I added a PR to fix the issues with `copy_inline()`. You are mentioned in the NEWS for providing the initial implementation. My implementation produces the same query but is a bit different (e.g. this uses S3 dispatch and supports the new `types` argument).

Thanks a lot for your effort! Would be great if you could test out my implementation (install via `install_github("tidyverse/dbplyr#982")`) and give feedback.

**Comment by ejneer** [comment]
superseded by #982

**Pull request closed without merging**
