### PR TITLE
Changed VARCHAR to VARCHAR2

### PR DESCRIPTION
**Pull request by washcycle**
Per

> VARCHAR Datatype
> Do not use the VARCHAR datatype. Use the VARCHAR2 datatype instead. Although the VARCHAR datatype is currently synonymous with VARCHAR2, the VARCHAR datatype is scheduled to be redefined as a separate datatype used for variable-length character strings compared with different comparison semantics.

https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements001.htm

### CODE REVIEW

**Comment by hadley** [comment]
Can you please update the tests too?

**Comment by washcycle** [comment]
Done. Let me know if there is anything else. Or if this wasn't want you meant.

**Comment by hadley** [comment]
Looks good, thanks! To finish it off, can you please add a bullet to NEWS? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
