### PR TITLE
Fix mysql odbc

### LINKED ISSUE #238: Syntax error with `copy_to` for MariaDB database backend
I'm not 100% certain how to trace this any further. It looks like `copy_to` has trouble w/ SQL syntax for the MariaDB / MySQL connection. Using latest MariaDB docker image and the `odbc` package w/ the RStudio Pro drivers.

```
> tb <- copy_to(dbcon, testdata, "test2") %>% show_query()
Error: <SQL> 'ANALYZE `test2`'
  nanodbc/nanodbc.cpp:1587: 42000: [RStudio][MySQL] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`test2`' at line 1 
> tb <- copy_to(dbcon, testdata, "test2") %>% show_query()
Error: <SQL> 'CREATE TEMPORARY TABLE `test2` (
  `fld_factor` TEXT,
  `fld_datetime` TEXT,
  `fld_date` TEXT,
  `fld_time` TEXT,
  `fld_binary` INTEGER,
  `fld_integer` INTEGER,
  `fld_double` DOUBLE,
  `fld_character` TEXT,
  `fld_logical` INTEGER
)
'
  nanodbc/nanodbc.cpp:1587: 42S01: [RStudio][MySQL] Table 'test2' already exists 
```

### PR DESCRIPTION
**Pull request by colearendt**
Add S3 methods for `odbc` connections to MySQL
Close #238

### CODE REVIEW

**Comment by colearendt** [comment]
Build failure is on R devel and looks spurious - probably just needs to be restarted

**Comment by hadley** [comment]
Can you please remove 8146465?

**Comment by colearendt** [comment]
Done!

**Comment by hadley** [comment]
Can you please add a bullet to NEWS? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Pull request merged**
