### PR TITLE
Fixes Oracle is.na issue, adds tests

### PR DESCRIPTION
**Pull request by edgararuiz**
Fixes https://github.com/tidyverse/dplyr/issues/3166

### CODE REVIEW

**Comment by edgararuiz** [comment]
PTAL @hadley

**Comment by edgararuiz** [comment]
@hadley - Please hold off reviewing this PR.  I would like to check this fix against an open connection with Oralce, and using `!is.na()`.

**Comment by edgararuiz** [comment]
@hadley  - This fix has the same deficiency as the one that's currently merged to master for MS SQL.  But I think it is still valuable for Oracle users.  Should I go ahead and update the code to use `sql_expr` instead of `build_sql`, or would you rather close it and find a solution that will work with normal and negated `is.na()`?

**Comment by hadley** [comment]
Does `NOT(1)`/`NOT(0)` also fail in Oracle?

**Comment by edgararuiz** [comment]
Yes, it looks that way:

```
> dbGetQuery(con, "SELECT NOT(0) from mtcars12")
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: HY000: ORA-00936: missing expression
 
> dbGetQuery(con, "SELECT NOT(1) from mtcars12")
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: HY000: ORA-00936: missing expression
 
> dbGetQuery(con, "SELECT 'hello'from mtcars12")
  'HELLO'
1   hello
```

**Comment by edgararuiz** [comment]
I just thought about testing `1` w/o a NOT, and that worked:

```
> dbGetQuery(con, "SELECT 1 from mtcars12")
  1
1 1
```

**Comment by edgararuiz** [comment]
That's correct

**Comment by hadley** [comment]
Per slack discussion

**Pull request closed without merging**
