### PR TITLE
add support for yday and quarter to PostgreSQL backend

### PR DESCRIPTION
**Pull request by derekmorr**
This adds support for the lubridate `yday()` function to the PostgreSQL backend.

### CODE REVIEW

**Comment by derekmorr** [comment]
I'm not sure why this build is failing. It's only failing for one version of R when building the vignette, but I can't see how anything I changed would affect that.

**Comment by hadley** [comment]
I'll take a look.

**Comment by hadley** [comment]
Looks like it was fixed upstream.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
