### PR TITLE
Fix na_if Translation for SQLite

### PR DESCRIPTION
**Pull request by cwarden**
Transalte na_if to NULLIF rather than NULL_IF when using a SQLite
connection.

### CODE REVIEW

**Comment by hadley** [comment]
Can you please also add a bullet to NEWS?

**Comment by cwarden** [comment]
Does d242c59 look ok, @hadley?  Would you like me to squash the commits?

**Comment by hadley** [comment]
Can you please remove the headers? I add them prior to release based on what ends up being in the release

**Comment by hadley** [comment]
(And no need to squash - I'll do that when I merge)

**Comment by hadley** [comment]
Perfect, thanks!

**Pull request merged**
