### PR TITLE
Use copy_inline() by default in memdb_frame()

### PR DESCRIPTION
**Pull request by krlmlr**
Should `auto_copy.tbl_sql()` also use `copy_inline()` ?

### CODE REVIEW

**Comment by mgirlich** [comment]
The following test fails

```r
test_that("can get 0 rows", {
  db <- memdb_frame(x = 1)
  out <- collect(head(db, 0))
  expect_equal(out, tibble(x = double()))
})
```

and shows one issue with SQLite and the values clause: it is not completely type stable :-/

**Comment by mgirlich** [comment]
The tests fail because of type instability for 0 rows tables in SQLite. I did not yet have a closer look whether this is because of SQLite itself or because of RSQLite. @krlmlr can you have a look at that?

If this cannot be fixed in RSQLite then we could use `copy_to()` for 0 row data frames.

**Comment by krlmlr** [comment]
I'm no longer sure that `copy_inline()` is really the right thing to do for SQLite databases, let's shelve it for now. Sorry for the noise.

**Comment by mgirlich** [comment]
This might still be an option for `auto_copy()` though. Maybe as opt-in via `*_join(copy = "inline")`? What do you think?

**Comment by krlmlr** [comment]
Still not sure. I prefer preparing the RHS of the join in advance and store it in a variable before joining, and never use auto-copy.

**Pull request closed without merging**
